package mess.exception

class MathArithmeticException(msg: String, cause: String) extends RuntimeException(msg){

}
